# Generated by Django 3.0.5 on 2020-04-12 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
