# Generated by Django 3.0.5 on 2020-04-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200413_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
