# Generated by Django 3.0.5 on 2020-04-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20200417_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
