# Generated by Django 3.0.5 on 2020-04-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20200417_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Reviews',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='book.Book'),
        ),
    ]
