# Generated by Django 3.0.5 on 2020-04-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20200418_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='description_cmt',
        ),
    ]
