# Generated by Django 3.0.5 on 2020-04-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20200418_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description_cmt',
            new_name='description',
        ),
    ]
