# Generated by Django 3.0.5 on 2020-04-20 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0015_auto_20200418_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='book.Book'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unread'), (1, 'Reading'), (2, 'Read')], default=0),
        ),
        migrations.AlterField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
